; BOOT SECTOR DO SISTEMA OPERACIONAL EMON 0.0.0.0.1
[ORG 0x7C00]

; CONSTANTE COM O ENDEREÇO DA POSIÇÃO ONDE O KERNEL SERÁ COLOCADO NA MEMÓRIA
ENDERECO_KERNEL EQU 0x1000

; SALVAMOS O IDENTIFICADOR DO DISPOSITIVO DE INICIALIZAÇÃO NA MEMÓRIA
MOV [DRIVE_BOOT], DL
; PREPARAMOS A PILHA DO SETOR DE BOOT
MOV BP, 0x9000 ; A BASE DA PILHA FICARÁ NO ENDEREÇO 0x9000
MOV SP, BP ; A PILHA COMEÇA COM SEU TOPO APONTANDO PARA A SUA BASE

; COMEÇAMOS EM MODO REAL 16 BITS
MOV BX, MENSAGEM_REAL_MODE

CALL CARREGAR_KERNEL ; FUNÇÃO DEFINIDA MAIS ABAIXO
CALL MUDAR_PARA_MODO_PROTEGIDO ; FUNÇÃO NO ARQUIVO modo32.asm
JMP $

; INCLUÍMOS OS DEMAIS ARQUIVOS NECESSÁRIOS
; %INCLUDE "imprime.asm"
; %INCLUDE "imprime_hexa.asm"
%INCLUDE "ler_disco.asm"
%INCLUDE "gdt32.asm"
%INCLUDE "imprime32.asm"
%INCLUDE "modo32.asm"

[BITS 16]
CARREGAR_KERNEL:
    ; LEREMOS O KERNEL NO DISCO USANDO A FUNÇÃO ler_disco.asm
    MOV BX, MENSAGEM_KERNEL
    CALL IMPRIME
    CALL IMPRIME_QUEBRA

    ; COLOCA O KERNEL LIDO NA POSIÇÃO CORRETA DA MEMÓRIA
    MOV BX, ENDERECO_KERNEL
    MOV DH, 2 ; A QUANTIDADE DE SETORES A SEREM LIDOS NO 
    MOV DL, [DRIVE_BOOT]
    CALL LER_DISCO
    RET

[BITS 32]
INICIAR_MP:
    ; MUDANÇA PARA 32 BITS (MODO PROTEGIDO)
    MOV EBX, MENSAGEM_PROTECTED
    CALL IMPRIME_MP
    CALL ENDERECO_KERNEL ; PASSAMOS O CONTROLE AO KERNEL
    JMP $

DRIVE_BOOT DB 0
MENSAGEM_REAL_MODE DB "EMON INICIADO EM 16 BITS (MODO REAL)", 0
MENSAGEM_PROTECTED DB "EMON EM 32 BITS (MODO PROTEGIDO)", 0
MENSAGEM_KERNEL DB "CARREGANDO O KERNEL NA MEMORIA...", 0

; FINAL DO BOOT SECTOR
TIMES 510-($-$$) DB 0
DW 0xAA55