; FUNÇÃO PARA IMPRESSÃO NA TELA EM MODO PROTEGIDO (32 BITS)
[BITS 32] ; INDICA QUE O CÓDIGO SERÁ ESCRITO E EXECUTADO EM MODO 32 BITS

; NOVIDADE: CONSTANTES EM ASSEMBLY!
MEMORIA_DE_VIDEO    EQU   0xB8000 ; ENDEREÇO DA MEMÓRIA DE VIDEO MODO TEXTO
BRANCO_EM_PRETO     EQU   0x0F    ; VALOR HEXA PARA TEXTO BRANCO NO FUNDO PRETO
VERMELHO_EM_PRETO   EQU   0x0C
VERDE_EM_PRETO      EQU   0x0D ; TALVEZ

IMPRIME_MP: ; IMPRIME EM MODO PROTEGIDO
    PUSHA
    MOV EDX, MEMORIA_DE_VIDEO ; EDX É O DX COM 32 BITS DE TAMANHO

IMPRIME_MP_LOOP:
    MOV AL, [EBX] ; EBX CONTÉM O ENDEREÇO DO CARACTERE A SER IMPRESSO
    MOV AH, BRANCO_EM_PRETO ; HEXA PARA COR

    CMP AL, 0 ; COMPARAÇÃO PARA VERIFICAR SE CHEGAMOS AO FINAL DA STRING
    JE IMPRIME_MP_FIM ; SE CHEGAMOS A FINAL, SALTA PARA "IMPRIME_MP_FIM". SE NÃO TERMINOU, CONTINUA...

    MOV [EDX], AX ; ARMAZENA NA POSIÇÃO DE MEMÓRIA EM EDX O CARACTERE E O CÓDIGO DE COR DESEJADO
    ADD EBX, 1 ; AVANÇA PARA O PRÓXIMO CARACTERE
    ADD EDX, 2 ; AVANÇA PARA A PRÓXIMA POSIÇÃO DA MEMÓRIA DE VÍDEO
    JMP IMPRIME_MP_LOOP ; REPETE O LAÇO

IMPRIME_MP_FIM: ; CHEGOU AO FIM
    POPA
    RET