; PROCEDIMENTOS PARA ENTRAR EM MODO PROTEGIDO (32-BITS)
; COMEÇAMOS EM MODO REAL (16 BITS)
[BITS 16]
MUDAR_PARA_MODO_PROTEGIDO:
    CLI ; COMEÇAMOS DESABILITANDO AS INTERRUPÇÕES DO PROCESSADOR
    ; ESTE COMANDO "CARREGA" A GDT NO PROCESSADOR
    ; PARA ALTERNAR PARA MODO PROTEGIDO DEVEMOS SETAR UM BIT NO REGISTRADOR CR0
    LGDT [GDT_DESCRITOR]
    MOV EAX, CR0
    OR EAX, 0X1
    MOV CR0, EAX
    JMP SEGMENTO_CODIGO:INICIAR_MODO_PROTEGIDO

; MUDAMOS PARA MODO PROTEGIDO (32 BITS)
[BITS 32]
INICIAR_MODO_PROTEGIDO:
    MOV AX, SEGMENTO_DADOS
    ; ATUALIZAMOS OS REGISTRADORES DE SEGMENTO
    MOV DS, AX
    MOV SS, AX
    MOV ES, AX
    MOV FS, AX
    MOV GS, AX
    
	MOV EBP, 0X90000 ; ATUALIZA O ENDEREÇO DA PILHA
    MOV ESP, EBP

    CALL INICIAR_MP
