[ORG 0x7C00]
MOV BP, 0x8000 ; BASE POINTER: ENDEREÇO DA BASE DA PILHA
MOV SP, BP ; SP: STACK POINTER PONTEIRO DO TOPO DA PILHA NO INÍCIO, A PILHA ESTÁ VAZIA, ENTÃO O TOPO É IGUAL À BASE

MOV BX, 0x9000 ; POSIÇÃO DA MEMÓRIA ONDE FICARÃO OS SETORES LIDOS NO DISCO (ES:BX 0x0000:0x9000)
MOV DH, 2 ; QUEREMOS LER DOIS SETORES BIOS VAI SETAR AUOTMATICAMENTE DL PARA O DISPOSITIVO DE BOOT
MOV DL, 0x80 ; NÚMERO DO HD

CALL LER_DISCO

MOV DX, [0x9000] ; COMEÇO DO SETOR 2
CALL IMPRIME_HEXA
CALL IMPRIME_QUEBRA

MOV DX, [0x9000 + 512] ; COMEÇO DO SETOR 3
CALL IMPRIME_HEXA
CALL IMPRIME_QUEBRA

JMP $

%INCLUDE "ler_disco.asm"

; PREENCHE O SETOR DE BOOT E NO FINAL COLOCA O MAGIC NUMBER
TIMES 510-($-$$) DB 0
DW 0xAA55

; CONTEÚDO PARA O SEGUNDO SETOR
TIMES 256 DW 0xCAFE
; CONTEÚDO PARA O TERCEIRO SETOR
TIMES 256 DW 0xFADA