MOV AH, 0x0E ; CÓDIGO RELATIVO À IMPRESSÃO DE CARACTERES

MOV BP, 0x8000 ; ENDEREÇO PARA A PILHA (STACK) DO PROGRAMA LONGE DO LOCAL ONDE FICARÁ O CÓDIGO DO BOOT SECTOR (0x7C00)
               ; ENDEREÇO SEGURO, NÃO VAI TER NADA LÁ
               ; BP = BASE POINTER: REGISTRADOR QUE ARMAZENA O ENDEREÇO INICIAL A PILHA (OU SEJA, SUA BASE)

MOV SP, BP ; SP = STACK POINTER: REGISTRADOR QUE GUARDA O ENDEREÇO DO TOPO DA PILHA (NO INÍCIO DO PROGRAMA O TOPO É IGUAL À BASE)

PUSH 'A'
PUSH 'B'
PUSH 'C' ; EMPILHA OS VALORES PARA OS CARACTERES A, B, C

MOV AL, [0x7FFE] ; 0x8000 - 2 = 0x7FFE
INT 0x10 ; O QUE SERÁ IMPRESSO? R: A

; DESEMPILHAMOS A LETRA NO TOPO ('C') E IMPRIMIMOS
POP BX
MOV AL, BL
INT 0x10

; DESEMPILHAMOS A LETRA SEGUINTE ('B')
POP BX
MOV AL, BL
INT 0x10

; DESEMPILHAMOS 'A'
POP BX
MOV AL, BL
INT 0x10

JMP $ ; VERSÃO SIMPLIFICADA DO BOOT INFINITO (LOOP)
TIMES 510-($-$$) DB 0 ; ARMAZENA ZEROS PARA PREENCHER 512 BYTES
DW 0xAA55 ; ARMAZENA NO FINAL O MAGIC NUMBER PARA O BOOT SECTOR