[ORG 0x7C00]

MOV AH, 0x0E

MOV AL, [LETRA] 
INT 0x10

MOV AL, [OUTRA]
INT 0x10

LETRA:
    DB 'Y'
OUTRA:
    DB 'Z'

JMP $ ; VERSÃO SIMPLIFICADA DO BOOT INFINITO (LOOP)
TIMES 510-($-$$) DB 0 ; ARMAZENA ZEROS PARA PREENCHER 512 BYTES
DW 0xAA55 ; ARMAZENA NO FINAL O MAGIC NUMBER PARA O BOOT SECTOR