; PRIMEIRA TENTATIVA DE BOOT SECTOR

LOOP:
    JMP LOOP ; PROVOCA UM LOOP INFINITO NO INÍCIO

TIMES 510-($-$$) DB 0 ; ARMAZENA ZEROS PARA PREENCHER 512 BYTES
DW 0XAA55 ; ARMAZENA NO FINAL O MAGIC NUMBER PARA O BOOT SECTOR