; IMPRIMINDO CARACTERES NO BOOT SECTOR

MOV AH, 0x0E ; CÓDIGO DO SERVIÇO DE TELETIPO DA BIOS

MOV AL, 'E'  ; CARACTERE A SER IMPRESSO
INT 0x10     ; GERA UM INTERRUPÇÃO PARA SERVIÇOS DE VÍDEO DA BIOS
MOV AL, 'M'
INT 0x10
MOV AL, 'O'
INT 0x10
MOV AL, 'N'
INT 0x10

JMP $ ; VERSÃO SIMPLIFICADA DO BOOT INFINITO (LOOP)

TIMES 510-($-$$) DB 0 ; ARMAZENA ZEROS PARA PREENCHER 512 BYTES
DW 0xAA55 ; ARMAZENA NO FINAL O MAGIC NUMBER PARA O BOOT SECTOR