; COMO FAREMOS REFERÊNCIA A POSIÇÕES DA MEMÓRIA DENTRO DO CÓDIGO DO BOOT SECTOR, TEMOS QUE LEMBRAR QUE ELE SERÁ COLOCADO
; NA POSIÇÃO 0x7C00 DA MEMÓRIA E ESSE VALOR DEVERÁ SER AUTOMATICAMENTE "SOMADO" AOS ENDEREÇOS DE MEMÓRIA LOCAIS.
[ORG 0x7C00]

MOV BX, SAUDACAO
CALL IMPRIME
CALL IMPRIME_QUEBRA

MOV BX, INFORMACOES
CALL IMPRIME
CALL IMPRIME_QUEBRA

MOV DX, 0xCAFE
CALL IMPRIME_HEXA
CALL IMPRIME_QUEBRA

MOV DX, 0x1A3B
CALL IMPRIME_HEXA
CALL IMPRIME_QUEBRA

JMP $

%INCLUDE "imprime_hexa.asm"

SAUDACAO:
    DB "BEM-VINDO AO EMON", 0

INFORMACOES:
    DB "SISTEMA OPERACIONAL DO BCC6A", 0

VERSAO:
    DB "VERSAO 0.1"

TIMES 510-($-$$) DB 0
DW 0xAA55