; PRIMEIRA VERSÃO DO BOOT SECTOR DO NOSSO S.O. QUE FARÁ A TRANSIÇÃO PARA 32 BITS (POIS ELE COMEÇA EM 16 BITS)
[ORG 0x7C00]
MOV BP, 0x9000 ; ENDEREÇO DA BASE DA PILHA
MOV SP, BP ; NO INÍCIO, NO TOPO DA PILHA (SP) É A SUA BASE (BP)

MOV BX, MENSAGEM_MODO_REAL
CALL IMPRIME

; CHAMAMOS A MUDANÇA PARA 32 BITS (EM modo32.asm)
CALL MUDAR_PARA_MODO_PROTEGIDO
JMP $

%INCLUDE "imprime.asm"
%INCLUDE "gdt32.asm"
%INCLUDE "imprime32.asm"
%INCLUDE "modo32.asm"

INICIAR_MP:
    MOV EBX, MENSAGEM_MODO_PROTEGIDO
    CALL IMPRIME_MP
    JMP $

MENSAGEM_MODO_REAL DB "INICIANDO EM MODO REAL (16 BITS)"
MENSAGEM_MODO_PROTEGIDO DB "INICIANDO EM MODO PROTEGIDO (32 BITS)"

; RESTANTE DO BOOT SECTOR
TIMES 510-($-$$) DB 0
DW 0xAA55