MOV AH, 0x0E ; CÓDIGO DO SERVIÇO DE TELETIPO DA BIOS
MOV BX, LETRA  ; BX = 0x07
ADD BX, 0x7C00 ; BX = BX + 0x7C00
MOV AL, [BX] ; CARACTERE A SER IMPRESSO
INT 0x10        ; GERA UM INTERRUPÇÃO PARA SERVIÇOS DE VÍDEO DA BIOS

MOV BX, OUTRA
ADD BX, 0x7C00
MOV AL, [BX]
INT 0x10

LETRA:
    DB 'Y'
OUTRA:
    DB 'Z'

JMP $ ; VERSÃO SIMPLIFICADA DO BOOT INFINITO (LOOP)

TIMES 510-($-$$) DB 0 ; ARMAZENA ZEROS PARA PREENCHER 512 BYTES
DW 0xAA55 ; ARMAZENA NO FINAL O MAGIC NUMBER PARA O BOOT SECTOR