; IMPLEMENTAÇÃO DA GDT (GLOBAL DESCRIPTOR TABLE)
GDT_INICIO:
    ; A GDT DEVE COMEÇAR COM 8 BYTES (64 BITS) NULOS
    DD 0x0 ; DD: DEFINE DOUBLE (ARMAZENA UM VALOR DE 32 BITS)
    DD 0x0

; REFERÊNCIA ASSEMBLY!
; DB (DEFINE BYTE) ARMAZENA UM BYTE (8 BITS)
; DW (DEFINE WORD) ARMAZENA DOIS BYTES (16 BITS)
; DD (DEFINE DOUBLE) ARMAZENA QUATRO BYTES (32 BITS)
; DQ (DEFINE QUAD) ARMAZENA OITO BYTES (64 BITS)

; ENTRADA NA GDT PARA O SEGMENTO DE CÓDIGO
GDT_CODIGO:
    DW 0xFFFF ; PRIMEIRA PARTE DO LIMITE (TAMANHO): BITS 0 - 15
    DW 0x0 ; PRIMEIRA PARTE DO ENDEREÇO BASE: BITS 0 - 15
    DB 0x0 ; SEGUNDA PARTE DO ENDEREÇO BASE: BITS 16 - 23

    ; PRIMEIRA SEQUÊNCIA DE FLAGS: PRESENTE(1) PRIVILÉGIO(00) TIPO(1) CÓDIGO(1) CONFORMIDADE(0) LEITURA(1) ACESSADO(0)
    DB 10011010b ; O "b" NO FINAL INDICA VALOR BINÁRIO

    ; SEGUNDA SEQUÊNCIA DE FLAGS: GRANULARIDADE(1) 32-BITS(1) 64-BITS(0) AVL(0) E O RESTANTE DO LIMITE/TAMANHO(1111)
    DB 11001111b
    DB 0x0 ; ÚLTIMA PARTE DO ENDEREÇO BASE (BITS 24 - 31)

; ENTRADA NA GDT PARA O SEGMENTO DE DADOS. PARA SIMPLIFICAR, ELE FICARÁ UNIFICADO COM O SEGMENTO DE CÓDIGO
GDT_DADOS:
    DW 0xFFFF
    DW 0x0
    DB 0x0
    DB 10010010b ; ÚNICA DIFERENÇA: QUINTO BIT É 0 (SEGMENTO DE DADOS)
    DB 11001111b
    DB 0x0

GDT_FIM:

GDT_DESCRITOR:
    DW GDT_FIM - GDT_INICIO - 1
    DD GDT_INICIO

; CONSTANTES QUE SERÃO USADAS POSTERIORMENTE
SEGMENTO_CODIGO EQU GDT_CODIGO - GDT_INICIO
SEGMENTO_DADOS EQU GDT_DADOS - GDT_INICIO