; CÓDIGO PARA UMA "FUNÇÃO"DE IMPRESSÃO DE STRINGS USANDO A BIOS
IMPRIME:
    PUSHA ; "PUSH ALL": EMPILHA OS VALORES DE TODOS OS REGISTRADORES

INICIO:
    MOV AL, [BX] ; ANTES DE CHAMAR A FUNÇÃO, COLOCAREMOS EM AL O ENDEREÇO DA STRING (EM BX) A SER IMPRESSA
    ; A INSTRUÇÃO ACIMA COLOCARÁ NO AL O VALOR DO PRIMEIO CARACTERE NO ENDEREÇO DA STRING
    
    CMP AL, 0 ; COMPARAMOS O VALOR DO CARACTERE EM AL COM 0
    JE FIM ; SE FOR 0, A STRING TERMINOU. SALTAMOS PARA "FIM"
           ; SE NÃO FOR 0, O PROGRAMA SEGUE PARA A PRÓXIMA INSTRUÇÃO

    MOV AH, 0x0E
    INT 0x10

    ADD BX, 1 ; ADICIONA 1 AO ENDEREÇO ARMAZENADO EM BX DE FORMA QUE AGORA ELE APONTA PARA O CARACTERE SEGUINTE NA STRING
    JMP INICIO ; "LOOP" QUE VOLTA AO INÍCIO PARA CONTINUAR IMPRIMINDO OS DEMAIS CARACTERES

FIM:
    POPA ; "POP ALL": DESEMPILHA E "DEVOLVE" OS VALORES A TODOS OS REGISTRADORES
    RET ; ENCERRA A "FUNÇÃO" E RETORNA AO PONTO DE ONDE FOI CHAMADA

IMPRIME_QUEBRA:
    PUSHA
    MOV AH, 0x0E
    MOV AL, 0x0A ; HEXADECIMAL DA QUEBRA DE LINHA
    INT 0x10
    MOV AL, 0x0D ; RETORNO DO CURSOR (CARRIAGE RETURN)
    INT 0x10
    POPA
    RET