[BITS 16]
MUDAR_PARA_MODO_PROTEGIDO:
    CLI ; DESABILITAMOS AS INTERRUPÇÕES DO PROCESSADOR
    LGDT [GDT_DESCRITOR] ; CARREGAMOS O GDT NO PROCESSADOR
    ; PARA MUDAR A CPU PARA 32 BITS DEVEMOS SETAR UM BIT ESPECÍFICO EM UM REGISTRADOR CHAMADO CR0
    MOV EAX, CR0
    OR EAX, 0x01
    MOV CR0, EAX
    JMP SEGMENTO_CODIGO ; INICIAR MODO PROTEGIDO

[BITS 32]
INICIAR_MODO_PROTEGIDO:
    MOV AX, SEGMENTO_DADOS
    ; ATUALIZAMOS OS REGISTRADORES DE SEGMENTO
    MOV DS, AX
    MOV SS, AX
    MOV ES, AX
    MOV FS, AX
    MOV GS, AX